---
title: "July 9 Report"
author: "Hao"
date: "7/8/2019"
output:   
  html_document:
    number_sections: FALSE
    toc: true
    fig_width: 8
    fig_height: 6
    theme: paper
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

**My git repo of all notes**: [github](https://github.com/HaoWang47/MetagenomicsStudy);

**YouTube introductory video**: [Microbiome/Metagenome Analysis Workshop: Introduction to Metagenomics](https://www.youtube.com/watch?v=LUS62N7tSUU)

**Potentially useful R packages**: 

  - [dada2](https://benjjneb.github.io/dada2/);
  - [phyloseq: Analyze microbiome census data using R](https://joey711.github.io/phyloseq/); 
  - [Beginner's guide to using the DESeq2 package](Michael I Love, 2014, tutorial, Beginner's guide to using the DESeq2 package.pdf);

**Literature**

  - [Exact sequence variants should replace operational taxonomic units in marker-gene data analysis](https://www.nature.com/articles/ismej2017119), Benjamin J Callahan, Paul J McMurdie and Susan P Holmes, 2017, Nature;
  - [DADA2: High resolution sample inference from Illumina amplicon data](https://www.nature.com/articles/nmeth.3869), Benjamin J Callahan, Paul J McMurdie, Michael J Rosen, Andrew W Han, Amy Jo A Johnson, and Susan P Holmes, 2016, Nature;
  - [Temporal and spatial variation of the human microbiota during pregnancy](https://www.ncbi.nlm.nih.gov/pubmed/26283357), Daniel B. DiGiulio, Benjamin J. Callahan, Paul J. McMurdie, Elizabeth K. Costello, Deirdre J. Lyell, Anna Robaczewska, Christine L. Sun, Daniela S. A. Goltsman, Ronald J. Wong, Gary Shaw,
David K. Stevenson, [Susan P. Holmes](http://statweb.stanford.edu/~susan/papers/PNASRR.html), and David A. Relman, 2015, PNAS;
  - [Marine mammals harbor unique microbiotas shaped by and yet distinct from the sea](https://www.nature.com/articles/ncomms10516), Elisabeth M. Bik, Elizabeth K. Costello, Alexandra D. Switzer, Benjamin J. Callahan, Susan P. Holmes, Randall S. Wells, Kevin P. Carlin, Eric D. Jensen, Stephanie Venn-Watson & David A. Relmanl, 2016, Nature;
  - [Moderated estimation of fold change and dispersion for RNA-seq data with DESeq2](https://www.ncbi.nlm.nih.gov/pubmed/25516281), Michael I Love, Wolfgang Huber and Simon Anders, 2014, Genome Biology; 

